"""Install a local per-PC stub that launches ``library-sync watch``.

launchd / Task Scheduler / systemd must live on the computer so they can see
the volume appear. The stub does not hardcode ``H:``; it discovers the drive
by volume name (``Will Hunter Music``, ``HuntingSzn``) then runs watch from
``{DRIVE}/Scripts`` via the uv captured at install time.
"""

from __future__ import annotations

import getpass
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

from library_sync.mount import VOLUME_NAMES

LAUNCHD_LABEL = "com.huntingszn.library-sync.watch"
WINDOWS_TASK_NAME = "HuntingSzn library-sync watch"
SYSTEMD_UNIT = "library-sync-watch.service"

_STUB_NAME = "watch-stub.py"
_CMD_NAME = "watch-stub.cmd"


def local_data_dir() -> Path:
    """Per-user directory for the stub (always on the PC, never only on the HDD)."""
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "library-sync"
    if sys.platform == "win32":
        base = os.environ.get("LOCALAPPDATA") or str(Path.home() / "AppData" / "Local")
        return Path(base) / "library-sync"
    xdg = os.environ.get("XDG_DATA_HOME")
    if xdg:
        return Path(xdg) / "library-sync"
    return Path.home() / ".local" / "share" / "library-sync"


def launchd_plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LAUNCHD_LABEL}.plist"


def systemd_unit_path() -> Path:
    return Path.home() / ".config" / "systemd" / "user" / SYSTEMD_UNIT


def windows_task_xml_path() -> Path:
    return local_data_dir() / "watch-task.xml"


def resolve_uv() -> Path | None:
    """Absolute uv binary. Prefer ``uv.exe`` over a ``.cmd`` / ``.bat`` shim."""
    found = shutil.which("uv")
    if not found:
        return None
    path = Path(found)
    if path.suffix.lower() in {".cmd", ".bat"}:
        exe = path.with_suffix(".exe")
        if exe.is_file():
            path = exe
    return path.resolve()


def render_stub(uv: Path, path_env: str = "") -> str:
    """Stdlib-only launcher. ASCII so cp1252 consoles cannot crash it.

    Runs ``library-sync watch`` as a daemon (never ``--once``). A looping
    ``watch --once`` would republish to B2 every few seconds. If watch exits,
    wait POLL_S and start it again — do not treat exit 0 as a reason to rush.
    """
    names = ", ".join(repr(name) for name in VOLUME_NAMES)
    uv_literal = repr(str(uv))
    path_literal = repr(path_env)
    return f'''\
# Auto-generated by library-sync install-watch. Lives on this PC, not the HDD.
# Discovers the music drive by volume name, then runs library-sync watch.
from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

UV = {uv_literal}
VOLUME_NAMES = ({names})
PATH_PREFIX = {path_literal}
POLL_S = 5
CREATE_NO_WINDOW = 0x08000000


def _scripts_if_valid(root: Path) -> Path | None:
    scripts = root / "Scripts"
    if scripts.is_dir() and (scripts / "pyproject.toml").is_file():
        return scripts
    return None


def _is_bare_windows_root(path: Path) -> bool:
    text = str(path).rstrip("\\\\/")
    return len(text) == 2 and text[1] == ":" and text[0].isalpha()


def _macos_volume_name_ok(name: str) -> bool:
    if name in VOLUME_NAMES:
        return True
    for vol in VOLUME_NAMES:
        extra = name[len(vol):]
        if name.startswith(vol) and extra[:1] == " " and extra[1:].isdigit():
            return True
    return False


def _windows_letter_is_music(letter: str) -> bool:
    import ctypes

    kernel32 = ctypes.windll.kernel32  # type: ignore[attr-defined]
    kernel32.GetLogicalDrives.restype = ctypes.c_uint32
    kernel32.GetVolumeInformationW.argtypes = [
        ctypes.c_wchar_p,
        ctypes.c_wchar_p,
        ctypes.c_uint32,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_uint32,
    ]
    kernel32.GetVolumeInformationW.restype = ctypes.c_int
    try:
        mask = int(kernel32.GetLogicalDrives())
    except OSError:
        return False
    bit = ord(letter[:1].upper()) - ord("A")
    if bit < 0 or bit > 25 or not mask & (1 << bit):
        return False
    buf = ctypes.create_unicode_buffer(1024)
    root_s = letter[:1].upper() + ":\\\\"
    try:
        ok = kernel32.GetVolumeInformationW(root_s, buf, 1024, None, None, None, None, 0)
    except OSError:
        return False
    return bool(ok) and buf.value in VOLUME_NAMES


def find_scripts() -> Path | None:
    env = os.environ.get("MUSIC_DRIVE_ROOT")
    if env:
        root = Path(env)
        if sys.platform == "win32" and _is_bare_windows_root(root):
            if not _windows_letter_is_music(str(root).rstrip("\\\\/")[0]):
                root = None
        if root is not None:
            found = _scripts_if_valid(root)
            if found is not None:
                return found

    if sys.platform == "darwin":
        volumes = Path("/Volumes")
        for name in VOLUME_NAMES:
            found = _scripts_if_valid(volumes / name)
            if found is not None:
                return found
        try:
            for entry in volumes.iterdir():
                if _macos_volume_name_ok(entry.name):
                    found = _scripts_if_valid(entry)
                    if found is not None:
                        return found
        except OSError:
            pass
        return None

    if sys.platform == "win32":
        return _find_windows_scripts()

    user = os.environ.get("USER") or os.environ.get("USERNAME") or ""
    bases = [Path("/mnt"), Path("/media")]
    if user:
        bases.extend([Path("/media") / user, Path("/run/media") / user])
    for base in bases:
        for name in VOLUME_NAMES:
            found = _scripts_if_valid(base / name)
            if found is not None:
                return found
    return None


def _find_windows_scripts() -> Path | None:
    import ctypes
    import string

    kernel32 = ctypes.windll.kernel32  # type: ignore[attr-defined]
    kernel32.GetLogicalDrives.restype = ctypes.c_uint32
    kernel32.GetVolumeInformationW.argtypes = [
        ctypes.c_wchar_p,
        ctypes.c_wchar_p,
        ctypes.c_uint32,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_uint32,
    ]
    kernel32.GetVolumeInformationW.restype = ctypes.c_int
    buf = ctypes.create_unicode_buffer(1024)
    mask = kernel32.GetLogicalDrives()
    for i, letter in enumerate(string.ascii_uppercase):
        if not mask & (1 << i):
            continue
        root_s = letter + ":\\\\"
        try:
            ok = kernel32.GetVolumeInformationW(root_s, buf, 1024, None, None, None, None, 0)
        except OSError:
            continue
        if ok and buf.value in VOLUME_NAMES:
            found = _scripts_if_valid(Path(root_s))
            if found is not None:
                return found
    return None


def main() -> int:
    os.environ["PYTHONUTF8"] = "1"
    os.environ.setdefault("PYTHONIOENCODING", "utf-8")
    if PATH_PREFIX:
        os.environ["PATH"] = PATH_PREFIX + os.pathsep + os.environ.get("PATH", "")
    if sys.platform == "win32":
        try:
            import ctypes

            ctypes.windll.kernel32.FreeConsole()
        except (AttributeError, OSError):
            pass
    while True:
        scripts = find_scripts()
        if scripts is None:
            time.sleep(POLL_S)
            continue
        cmd = [UV, "run", "--package", "library-sync", "library-sync", "watch"]
        if sys.platform == "win32" and UV.lower().endswith((".cmd", ".bat")):
            cmd = [os.environ.get("COMSPEC", "cmd.exe"), "/c", *cmd]
        extra = dict()
        if sys.platform == "win32":
            extra["creationflags"] = CREATE_NO_WINDOW
        subprocess.call(cmd, cwd=str(scripts), **extra)
        time.sleep(POLL_S)


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render_windows_cmd(uv: Path, stub: Path, path_env: str = "") -> str:
    lines = [
        "@echo off\r\n",
        "set PYTHONUTF8=1\r\n",
        "set PYTHONIOENCODING=utf-8\r\n",
    ]
    if path_env:
        safe = path_env.replace('"', "")
        lines.append(f'set "PATH={safe};%PATH%"\r\n')
    lines.append(f'"{uv}" run --python 3.12 "{stub}"\r\n')
    return "".join(lines)


def render_launchd_plist(uv: Path, stub: Path, path_env: str) -> str:
    path_xml = _xml_escape(path_env)
    return f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" \
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{_xml_escape(str(uv))}</string>
    <string>run</string>
    <string>--python</string>
    <string>3.12</string>
    <string>{_xml_escape(str(stub))}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PYTHONUTF8</key>
    <string>1</string>
    <key>PYTHONIOENCODING</key>
    <string>utf-8</string>
    <key>PATH</key>
    <string>{path_xml}</string>
  </dict>
</dict>
</plist>
"""


def render_systemd_unit(uv: Path, stub: Path, path_env: str) -> str:
    exec_start = f"{shlex.quote(str(uv))} run --python 3.12 {shlex.quote(str(stub))}"
    return f"""\
[Unit]
Description=HuntingSzn library-sync drive watch (pull, index, publish; never deletes B2)
After=default.target

[Service]
ExecStart={exec_start}
Environment=PYTHONUTF8=1
Environment=PYTHONIOENCODING=utf-8
Environment=PATH={path_env}
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
"""


def render_windows_task_xml(
    command: Path,
    *,
    arguments: str | None = None,
    user_id: str | None = None,
    working_directory: Path | None = None,
) -> str:
    user_xml = _xml_escape(user_id) if user_id else ""
    user_block = f"      <UserId>{user_xml}</UserId>\n" if user_id else ""
    trigger_user = f"      <UserId>{user_xml}</UserId>\n" if user_id else ""
    args_block = ""
    if arguments:
        args_block = f"      <Arguments>{_xml_escape(arguments)}</Arguments>\n"
    wd_block = ""
    if working_directory is not None:
        wd_block = (
            f"      <WorkingDirectory>{_xml_escape(str(working_directory))}</WorkingDirectory>\n"
        )
    return f"""\
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>HuntingSzn library-sync: when the music drive is plugged in, \
pull from B2, incremental index, publish. Never deletes from B2.</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
{trigger_user}    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
{user_block}      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>false</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT10S</Interval>
      <Count>999</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{_xml_escape(str(command))}</Command>
{args_block}{wd_block}    </Exec>
  </Actions>
</Task>
"""


def _xml_escape(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _windows_rclone_dirs() -> list[str]:
    """Dirs where rclone often lives even when Task Scheduler PATH is stripped."""
    local = os.environ.get("LOCALAPPDATA") or str(Path.home() / "AppData" / "Local")
    return [
        str(Path.home() / ".local" / "bin"),
        str(Path(local) / "Microsoft" / "WinGet" / "Links"),
        str(Path(local) / "Programs" / "rclone"),
        str(Path(r"C:\Program Files\rclone")),
    ]


def _install_path_env(uv: Path) -> str:
    """PATH for GUI/login agents, which otherwise miss Homebrew / uv / rclone."""
    current = os.environ.get("PATH", "")
    extras: list[str] = [str(uv.parent)]
    rclone = shutil.which("rclone")
    if rclone:
        extras.insert(0, str(Path(rclone).resolve().parent))
    if sys.platform == "win32":
        extras.extend(_windows_rclone_dirs())
    else:
        extras.extend(["/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin"])
    parts: list[str] = []
    seen: set[str] = set()
    for part in extras + current.split(os.pathsep):
        if part and part not in seen:
            seen.add(part)
            parts.append(part)
    return os.pathsep.join(parts)


def _write(path: Path, contents: str, *, encoding: str = "utf-8") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding=encoding)


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, check=False, capture_output=True, text=True)


def install_watch(*, dry_run: bool = False) -> int:
    """Write the local stub and register launchd / Task Scheduler / systemd."""
    uv = resolve_uv()
    if uv is None:
        print(
            "Error: uv not found on PATH. Install uv, then re-run install-watch.",
            file=sys.stderr,
        )
        return 1

    data_dir = local_data_dir()
    stub = data_dir / _STUB_NAME
    path_env = _install_path_env(uv)
    stub_src = render_stub(uv, path_env)

    print("library-sync install-watch")
    print(f"  uv:   {uv}")
    print(f"  stub: {stub}")
    print("  volumes: " + ", ".join(VOLUME_NAMES))
    print("  pipeline: pull -> incremental index -> publish (copy --update, never deletes B2)")
    if shutil.which("rclone") is None:
        print(
            "  warning: rclone not on PATH at install time; the login task "
            "searches common rclone dirs, but re-run install-watch after installing rclone",
            file=sys.stderr,
        )
    print()

    if dry_run:
        print("[dry-run] would write stub and register the login service")
        return 0

    _write(stub, stub_src)
    if sys.platform == "win32":
        return _install_windows(uv, stub, path_env)
    if sys.platform == "darwin":
        return _install_macos(uv, stub, path_env)
    return _install_linux(uv, stub, path_env)


def _install_macos(uv: Path, stub: Path, path_env: str) -> int:
    plist = launchd_plist_path()
    _write(plist, render_launchd_plist(uv, stub, path_env))
    uid = os.getuid()
    domain = f"gui/{uid}"
    _run(["launchctl", "bootout", domain, str(plist)])
    loaded = _run(["launchctl", "bootstrap", domain, str(plist)])
    if loaded.returncode != 0:
        legacy = _run(["launchctl", "load", "-w", str(plist)])
        if legacy.returncode != 0:
            print("Wrote plist but launchctl load failed:", file=sys.stderr)
            print(loaded.stderr or legacy.stderr, file=sys.stderr)
            print(f"Load manually: launchctl bootstrap {domain} {plist}")
            return 1
    kicked = _run(["launchctl", "kickstart", "-k", f"{domain}/{LAUNCHD_LABEL}"])
    if kicked.returncode != 0:
        _run(["launchctl", "start", LAUNCHD_LABEL])
    print(f"Installed LaunchAgent: {plist}")
    print("If the drive is already plugged in, watch will run after a short debounce.")
    print("Log: {DRIVE}/Scripts/data/watch.log")
    return 0


def _windows_user_id() -> str:
    user = os.environ.get("USERNAME") or getpass.getuser()
    domain = os.environ.get("USERDOMAIN")
    if domain and "\\" not in user:
        return f"{domain}\\{user}"
    return user


def _resolve_pythonw(uv: Path) -> Path | None:
    """GUI Python so Task Scheduler does not leave a console on the desktop."""
    proc = _run(
        [
            str(uv),
            "run",
            "--python",
            "3.12",
            "python",
            "-c",
            (
                "import sys; from pathlib import Path; "
                "p = Path(sys.executable).with_name('pythonw.exe'); "
                "print(p if p.is_file() else '')"
            ),
        ]
    )
    text = (proc.stdout or "").strip()
    if proc.returncode != 0 or not text:
        return None
    path = Path(text)
    return path if path.is_file() else None


def _install_windows(uv: Path, stub: Path, path_env: str) -> int:
    cmd_path = stub.with_name(_CMD_NAME)
    _write(cmd_path, render_windows_cmd(uv, stub, path_env), encoding="utf-8")
    pythonw = _resolve_pythonw(uv)
    user_id = _windows_user_id()
    if pythonw is not None:
        command = pythonw
        arguments = f'"{stub}"'
    else:
        command = cmd_path
        arguments = None
    xml_path = windows_task_xml_path()
    _write(
        xml_path,
        render_windows_task_xml(
            command,
            arguments=arguments,
            user_id=user_id,
            working_directory=stub.parent,
        ),
        encoding="utf-16",
    )
    created = _run(
        ["schtasks", "/Create", "/TN", WINDOWS_TASK_NAME, "/XML", str(xml_path), "/F"]
    )
    if created.returncode != 0:
        print("Wrote stub but schtasks failed:", file=sys.stderr)
        print(created.stderr or created.stdout, file=sys.stderr)
        print(
            f'Create manually: schtasks /Create /TN "{WINDOWS_TASK_NAME}" '
            f'/XML "{xml_path}" /F'
        )
        return 1
    _run(["schtasks", "/Run", "/TN", WINDOWS_TASK_NAME])
    print(f"Installed scheduled task: {WINDOWS_TASK_NAME}")
    print(f"  wrapper: {cmd_path}")
    print("If the drive is already plugged in, watch will run after a short debounce.")
    print("Log: {DRIVE}/Scripts/data/watch.log")
    return 0


def _install_linux(uv: Path, stub: Path, path_env: str) -> int:
    unit = systemd_unit_path()
    _write(unit, render_systemd_unit(uv, stub, path_env))
    _run(["systemctl", "--user", "daemon-reload"])
    enabled = _run(["systemctl", "--user", "enable", "--now", SYSTEMD_UNIT])
    if enabled.returncode != 0:
        print("Wrote unit but systemctl --user enable failed:", file=sys.stderr)
        print(enabled.stderr or enabled.stdout, file=sys.stderr)
        print(f"Enable manually: systemctl --user enable --now {SYSTEMD_UNIT}")
        return 1
    print(f"Installed systemd user unit: {unit}")
    print("If the drive is already plugged in, watch will run after a short debounce.")
    print("Log: {DRIVE}/Scripts/data/watch.log")
    return 0


def uninstall_watch(*, dry_run: bool = False) -> int:
    """Remove the login stub and service. Leaves watch.log on the drive alone."""
    data_dir = local_data_dir()
    stub = data_dir / _STUB_NAME
    cmd_path = data_dir / _CMD_NAME
    xml_path = windows_task_xml_path()
    plist = launchd_plist_path()
    unit = systemd_unit_path()

    print("library-sync uninstall-watch")
    if dry_run:
        print("[dry-run] would unregister the login service and delete the stub")
        return 0

    if sys.platform == "darwin":
        uid = os.getuid()
        _run(["launchctl", "bootout", f"gui/{uid}", str(plist)])
        _run(["launchctl", "unload", "-w", str(plist)])
        if plist.exists():
            plist.unlink()
            print(f"Removed {plist}")
    elif sys.platform == "win32":
        _run(["schtasks", "/End", "/TN", WINDOWS_TASK_NAME])
        removed = _run(["schtasks", "/Delete", "/TN", WINDOWS_TASK_NAME, "/F"])
        if removed.returncode == 0:
            print(f"Removed scheduled task: {WINDOWS_TASK_NAME}")
        if xml_path.exists():
            xml_path.unlink()
    else:
        _run(["systemctl", "--user", "disable", "--now", SYSTEMD_UNIT])
        if unit.exists():
            unit.unlink()
            print(f"Removed {unit}")
        _run(["systemctl", "--user", "daemon-reload"])

    for path in (stub, cmd_path):
        if path.exists():
            path.unlink()
            print(f"Removed {path}")
    return 0


def cmd_install_watch(args: object) -> int:
    return install_watch(dry_run=bool(getattr(args, "dry_run", False)))


def cmd_uninstall_watch(args: object) -> int:
    return uninstall_watch(dry_run=bool(getattr(args, "dry_run", False)))
